# Generated by Django 3.1.3 on 2020-11-15 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectureNotes', '0002_auto_20201114_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='course',
            new_name='note',
        ),
    ]
